### ISSUE TITLE
参考までに…

### ISSUE THREAD

**Issue by dmats97** [HIDE810/you-are-an-idiot#1]
こんにちは(・∀・)

m3dialib-CTRは内部で必要なこといろいろやってくれているので、
```m3d::Screen;```を実行すると15〜21行目、32〜44行目までを省略または簡潔化出来ますよ!

また、私の改造版m3dialibはスプライトアニメーションを実装しているので、
```
int Anim[] = {0, 1, -1};
spr.setAnimate(Anim, コマ切り替えに要する時間(単位:ms), true);

while(aptMainloop()){
    spr.updateSprites();
    scr.drawTop(spr);
    scr.render();
}
```
と書くとアニメーション出来ます.
以前から僕のコードを使ってくださっているようなので、もしよかったら参考にされてください!

**Comment by HIDE810** [comment]
いつもありがとうございます(^^)

早速ライブラリ使わせてもらいましたが使いやすい！処理も軽くなった様で、前の処理ではプログラム終了時エラー落ちしていたのですが、どうやらそれも改善された様です。早速更新させていただきましたm(*_ _)m

1つ質問なんですが、m3dialibのaudioのサンプルソースにloopというものがあったのですが、これって普通に音楽再生のループ処理のことですか？試しにそのソースをビルドしてみたのですが、音楽は流れるものの、どうやらループ処理がされていない様で…
もし分かる様でしたら幸いです。

**Comment by dmats97** [comment]
m3dialibはなかなか便利だったりするんですがメモリをガンガン食いつぶすのでスプライトがフルに使えないというデメリットも有ります。

m3dialibのサンプルソース、こちらで試してみるとNew3DSはそもそも音が流れず、New3DSLLで試すとループ再生されました。挙動が怪しいですね。

メンバ関数を見てみると場所指定(正確には時間指定)のループも出来るようなので、明示的に示すと上手く行くかな〜?とも思いました

**Comment by HIDE810** [comment]
返信ありがとうございます。
やっぱりめっちゃメモリ食ってますよね笑
自分もスプライトアニメーションと併用したかったのですが、ループ処理は無理でした。(New3DS)
確かにでも、用意されている以上、書き方によっては出来るかもしれませんね。
前よりは処理は軽くなっている様なので、また試してみようと思います(^^)
